### ISSUE TITLE
Syntax checking doesn't account for light themes

### ISSUE THREAD

**Issue by ark-** [rust-lang/sublime-rust#102]
I'm using the eiffel theme for my rust code and when I syntax check with a warning I get the following:

![image](https://cloud.githubusercontent.com/assets/6353339/19659726/f1598db2-9a24-11e6-9426-ac50ebe56d86.png)

I'm sure it's possible but I'm not sure how to change the colour theme for these errors.

**Comment by ark-** [comment]
Further investigation I see that in `add_error_phantom()` function on line 65 the error colour is selected. Perhaps this should be overridable with a settings parameter.

For example, I changed this line in my local add-in
```
            # Warning color
            base_color = "#ff6600"
```

and now it looks like:

![image](https://cloud.githubusercontent.com/assets/6353339/19660172/a5549f40-9a26-11e6-98c2-c3d095b075ad.png)

**Comment by ark-** [comment]
Proposed a PR for this issue.

One down side is that this does not attempt to error check the color hex strings taken from the settings file, however I never noticed any checking on existing settings attributes. As such I deemed this sufficient.

**Comment by wbond** [comment]
The Phantoms functionality in Sublime Text adds a `light` or `dark` class to the `<body>` tag to allow handling things like this. Ideally CSS would be written to handle this.

I haven't looked at the current implementation of phantoms, but ideally there would be a way to use the color scheme's colors (via http://www.sublimetext.com/docs/3/minihtml.html#variables) for the text.

**Comment by ark-** [comment]
The light or dark class don't seem to be mentioned in your link. Are you suggesting we define a `body.dark` and `body.light` with the `color` attribute set accordingly in a global css scope? Where would this be defined?

I trialled the predefined variables mentioned in the link (which I now use as the defaults in the PR #103). However on the built in colour scheme "eiffel", the `var(--yellowish)` came out green? As such I decided these alone weren't a sufficient solution.

**Comment by wbond** [comment]
The pre-defined CSS variables are going to select the closest color in the scheme to the named color. It uses HSL color space to pick the closest color. Color scheme authors can also override these values with explicit values in the `popupCss` and `phantomCss` keys of the color scheme. Usually, however, the default values at the very least won't look garish, even if they aren't a specific hue you want to use. Ultimately it allows the user (and color scheme authors) to customize a color scheme rather than forking your project and editing Python files.

It is very possible there isn't documentation about the `.light` and `.dark` classes yet, I can get that added. In fact, I just looked at the implementation and it appear I was incorrect. The classes are on the `html` tag, not `body`. In short, you should create a `<style></style>` block in your HTML which includes selectors using `html.light` and `html.dark` to pick what colors you want to use for light or dark backgrounds. For instance, you may decide to use `--yellowish` with a dark background, but `--redish` with a light background. If you use https://packagecontrol.io/packages/PackageResourceViewer, you can inspect the `exec.py` file in the Default package. It contains an example of CSS targeting light and dark color schemes.

**Comment by ark-** [comment]
Closed with #103

**Comment by Jayflux** [comment]
@ark-  this has now been released
https://github.com/rust-lang/sublime-rust/releases/tag/v1.0.2

**Comment by ark-** [comment]
Great news! Thanks
