### ISSUE TITLE
Highlighting failure with struct field attributes

### ISSUE THREAD

**Issue by dimfeld** [rust-lang/sublime-rust#120]
See screenshot below. All the fields with `serde` attributes don't have highlighting on `pub`. I'm not sure if the upcoming changes in #116 take care of this. Also The `#[serde...` lines aren't colored gray, while like the `#[derive]` line at the top of the struct is.  FWIW I don't consider this particularly important :) 

EDIT: You can't see it here, but I have another similar structure that has some `pub name: Option<u8>` types, and on those the `u8` actually is highlighted properly, so this doesn't affect the entire line, just the `pub` at the start, it seems.

<img width="391" alt="screenshot 2016-11-16 17 59 56" src="https://cloud.githubusercontent.com/assets/1369558/20375970/e43ebfee-ac26-11e6-974b-e3b0a4d1e582.png">

**Comment by Jayflux** [comment]
@dimfeld  This is fixed in https://github.com/rust-lang/sublime-rust/pull/124 please pull that branch and try.

Looks like attribute comments were only defined in the global scope, so would no longer exist once you go inside a struct. I've now attached it with the rest of the comment definitions.

It may clash with @dten's work on the sublime-syntax file, but was a straight forward fix

**Comment by dimfeld** [comment]
Yep, that works for me. Looks much better. Thanks!

**Comment by Jayflux** [comment]
@dimfeld  I will try and get that fix into master this weekend

**Comment by dimfeld** [comment]
Thanks for pushing this through!
