### ISSUE TITLE
How to select a browser?

### ISSUE THREAD

**Issue by mistydemeo** [rust-lang/sublime-rust#194]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
2.0.1

### Operating system
A good example is:
OS Name	macOS
Version	10.12.6 16G29

Is it possible to select which web browser to use when opening documentation pages? I noticed that the doc links in warnings/errors are always opening in Firefox for me, whereas my default browser is set to Safari in the OS.

**Comment by ehuss** [comment]
The latest macOS update 10.12.5 released a few days ago broke `osascript` used by Python to open the web browser.  See [issue30392](https://bugs.python.org/issue30392).  Someone mentions that it appears to be fixed in the 10.12.6 beta.

Unfortunately, the ability to choose the browser using an environment variable also seems to be broken (see [issue24955](https://bugs.python.org/issue24955)).  Ugh.  So, I guess wait until 10.12.6 is released?

**Comment by ehuss** [comment]
I updated to 10.12.6, and it seems to be fixed now.  Can you verify what happens when you run this command in a terminal?

```echo "open location \"http://www.google.com/\"" | osascript```

This should open a web page in your default browser.  This is the mechanism that Python uses.

**Comment by mistydemeo** [comment]
I must have tested before upgrading - can confirm this works now. Thanks!
