### ISSUE TITLE
Should jump to first error even when there are warnings

### ISSUE THREAD

**Issue by Boscop** [rust-lang/sublime-rust#199]
When I get some warnings and some errors during a build and I press F4, it should jump to the first error (and then step from there).
Currently it jumps to the first warning which is often something trivial like `unused import`.
This behavior is annoying, I want to fix the errors first because they have higher priority...

(IIRC it used to be the case that F4 jumps to the first error in the past, but maybe I remember wrong.)

**Comment by ehuss** [comment]
You're right.  I'll look into it, thanks!

**Comment by Boscop** [comment]
Thanks. 
Also, it doesn't jump to the current error's description in the error output anymore when I step through errors with F4. 
Btw, it doesn't use the error messages that contain code anymore. Is this a bug or intended? Every error just has one line now...

**Comment by ehuss** [comment]
That is intended, at least for now.  The reason is that it now uses the JSON output from the compiler to extract the information so that it can show inline phantoms.  The compiler cannot currently output both JSON and text.  There is some discussion going on about refactoring and extracting the code that is responsible for rendering the text, but I think it will be a long ways off before that is ready.

**Comment by Boscop** [comment]
The problem is, often the inline error doesn't fit into the width of my sublime window when I have two side by side which is most of the time, then the inline error is cut off/unreadable and I have to rely on the error output window.
So it would be really helpful to have both again!

**Comment by ehuss** [comment]
I've been thinking about that, too.  What do you think if the inline message was displayed all the way to the left, instead of aligned with the column of where the error appears?  Like this:

![image](https://user-images.githubusercontent.com/43198/29478867-fcdf448a-8423-11e7-9eaf-4d7bc1302d85.png)


I think this would make it more readable in the common case, but has the drawback that if the error region is far to the right, then F4 will horizontally scroll past the message.

Another thing I've been considering is word-wrapping long messages.  There are some cases where rust can spit out some very long messages.  However, this has the drawback that the message may include a suggested code replacement, and it may display invalid code if word-wrapped incorrectly.

**Comment by Boscop** [comment]
I think displaying the error message all the way to the left is a better solution than word wrapping.
Why would this happen: "if the error region is far to the right, then F4 will horizontally scroll past the message"?

**Comment by ehuss** [comment]
> Why would this happen

If you have a really long line, the message will appear for to the left of the highlighted region, like this:

![image](https://user-images.githubusercontent.com/43198/29480737-695d9746-842f-11e7-86f3-4b8b2ba22381.png)

Unfortunately Sublime does not offer much control over the placement, so I think this problem will occur one way or another.

**Comment by Boscop** [comment]
Ah, I always have wordwrapping turned on for code. No horizontal scrolling.

**Comment by Boscop** [comment]
Can't the inline error be always aligned to the left of the viewport (regardless of horizontal scroll pos)?

**Comment by ehuss** [comment]
> Can't the inline error be always aligned to the left of the viewport (regardless of horizontal scroll pos)?

Not that I know of.  Sublime only allows you to place it directly below a specific column, or inline.
