### ISSUE TITLE
Add support for Doc-comment highlighting

### ISSUE THREAD

**Issue by wldcordeiro** [rust-lang/sublime-rust#38]
Doc-comments allow markdown within them it'd be nice if they reflected that at least somewhat and looked different from normal comments.

**Comment by gbersac** [comment]
Interesting feature ! I'd love that.

**Comment by diaphore** [comment]
Highlighting the whole comment in a different color could use the `comment.block.documentation` scope found in the [official syntax packages](https://github.com/sublimehq/Packages) (no `comment.line.documentation` oddly ... maybe in the wild) then it's a matter of the color scheme supporting it.

As for including markdown, I think the official implementation is not compatible for the most part since a lot of the markup is relative to the beginning of the line which is already set to `///`.

**Comment by petrochenkov** [comment]
Doc comments are marked as `comment.block.documentation`, but none of the default color schemes renders it different from normal comments, so I believe this issue belongs to something else and not this package
