### ISSUE TITLE
Upstream to Sublime core

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/sublime-rust#72]
Should we upstream this to the main Sublime repo? https://github.com/sublimehq/Packages

cc @brson @nrc @glennw

**Comment by dten** [comment]
Wouldn't that potentially slow things even more

**Comment by Manishearth** [comment]
What would it slow? It would be nice for people to get Rust highlighting on their editor by default without installing extra plugins. I'm assuming they are willing to accept improvements via PRs.

**Comment by nrc** [comment]
Sure, let's try and see what they say.

**Comment by Manishearth** [comment]
I'll write up an issue and/or PR later then.

**Comment by brson** [comment]
I think upstreaming editor configs is good. We've done this before with Kate.

**Comment by Manishearth** [comment]
opened https://github.com/sublimehq/Packages/issues/178, will make a pr if there are no objections on that end

**Comment by gbersac** [comment]
This is a great idea !

**Comment by Manishearth** [comment]
This has happened. https://github.com/sublimehq/Packages/issues/178#issuecomment-197050427

We should probably do the upgrade note and rename as mentioned in the comment (perhaps staggered a bit so that it happens after the dev release). Who has publish access?

We should also mark this repo as deprecated.

**Comment by FichteFoll** [comment]
Remember that any older build than 3018 (the next) of ST will not have the Rust package shipped by default, so keeping this online is definitely still desirable.

I suggest adding an update notice asking users to uninstall the package instead of renaming, which would affect all users of older builds (including ST2).

If you want to be super fancy (recommended!), you could add a new "release channel" in the package_control_channel repo for the new version with that update notice and restrict it to users with a ST build of 3108 or greater, in which case the exact people who would be affected by it are informed.

I can let you in on some more details if you are interested and can't figure it out on your own.

**Comment by Jayflux** [comment]
I'm going to close this, as this has been released upstream.
However, we will continue to keep this repository active, and will eventually run under a new name 'Rust Enhanced' to not cause confusion and conflict with the Default/Rust package
